# Generated by Django 4.0.4 on 2022-05-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parser',
            new_name='ParserBook',
        ),
    ]
