# Generated by Django 4.0.4 on 2022-05-07 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0003_new'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
