# Generated by Django 4.0.4 on 2022-04-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("book", "0004_bookdetails_bookcomet")]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("РОМАНТИКА", "романтика"),
                    ("ФЭНТЕЗИ", "фентези"),
                    ("ДЕТЕКТИВ", "детектив"),
                    ("АНИМЕ", "аниме"),
                ],
                max_length=90,
                null=True,
            ),
        )
    ]
