# Generated by Django 4.0.4 on 2022-05-15 14:03

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FAMALE', 'Famale')], max_length=20)),
                ('country', models.CharField(choices=[('КЫРГЫЗЫСТАН', 'КЫРГЫЗЫСТАН'), ('РОССИЯ', 'РОССИЯ')], max_length=50)),
                ('sport', models.CharField(choices=[('ФУТБОЛ', 'Футбол'), ('КИБЕРСПОРТ', 'Киберспорт'), ('ХОКЕЙ', 'Хокей')], max_length=23)),
                ('emai', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
